fix: IndexError in fun time_and_event_synchronization
IndexError: index 0 is out of bounds for axis 0 with size 0

The error is caused by the fact that at the end of method __collect_event_time of class Conductor, when there are no events the, the size of array events_time is 0 because the correction provided by the statement

if self.events_time.size == 0:

is nullified by the following if statement

if np.isclose(self.events_time[0],0.0):

Therefore the correction of this bug is carried out in method __collect_event_time of class Conductor.

Class: Conductor
modified:   conductor.py