fix: ValueError in method conductor_solution
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Bug in method conductor_solution of class Simulation while changes in method __initialize_attributes of class Conductor.

Class: Conductor
modified:   conductor.py