fix: KeyError in method eval_tcs
KeyError: 'current_along'

The error is caused setting fag I0_OP_MODE = none in input file conductor_definitio.xlsx. Since now current_along (and not op_current) is used to evaluate the critical current density in method eval_tcs, it is fundamental to set its value to 0 in both nodal and Gauss points before the evaluation of the current sharing temperature also when I0_OP_MODE = none.
This explains why the fix is performed in mehod get_current of class SolidComponent.

Class: SolidComponent
modified:   solid_component.py